using System.IO.Compression;
using System.Text;
using PortfolioForge.Models;
using PortfolioForge.Services.Templates;

namespace PortfolioForge.Services;

public class PortfolioGenerator
{
    private readonly List<IPortfolioTemplate> _templates;
    private readonly Random _rng = new();

    public PortfolioGenerator(IEnumerable<IPortfolioTemplate> templates)
    {
        _templates = templates.ToList();
    }

    public IReadOnlyList<IPortfolioTemplate> Templates => _templates;

    public int TotalVariantCount => _templates.Sum(t => t.VariantCount);

    /// <summary>Pick a random (template, variant) combo, optionally excluding one to avoid repeats.</summary>
    public (IPortfolioTemplate Template, int Variant) PickRandom(IPortfolioTemplate? excludeTemplate = null, int? excludeVariant = null)
    {
        // Build list of all possible combos
        var combos = new List<(IPortfolioTemplate t, int v)>();
        foreach (var t in _templates)
            for (var i = 0; i < t.VariantCount; i++)
                combos.Add((t, i));

        // Exclude the current combo so randomize always changes something
        if (excludeTemplate != null && excludeVariant.HasValue)
        {
            combos.RemoveAll(c => c.t.Name == excludeTemplate.Name && c.v == excludeVariant.Value);
        }

        var pick = combos[_rng.Next(combos.Count)];
        return pick;
    }

    public IPortfolioTemplate GetByName(string name) =>
        _templates.First(t => string.Equals(t.Name, name, StringComparison.OrdinalIgnoreCase));

    public GeneratedPortfolio Generate(IPortfolioTemplate template, GitHubUser user, List<GitHubRepo> repos, int variant) =>
        template.Generate(user, repos, variant);

    /// <summary>Bundle the portfolio into a ZIP byte array suitable for download.</summary>
    public byte[] BuildZip(GitHubUser user, GeneratedPortfolio portfolio, string templateName, int variant)
    {
        using var ms = new MemoryStream();
        using (var archive = new ZipArchive(ms, ZipArchiveMode.Create, true))
        {
            AddEntry(archive, "index.html", portfolio.Html);
            AddEntry(archive, "style.css", portfolio.Css);
            AddEntry(archive, "script.js", portfolio.Js);
            AddEntry(archive, "README.md", BuildReadme(user, templateName, variant));
        }
        return ms.ToArray();
    }

    private static void AddEntry(ZipArchive archive, string name, string content)
    {
        var entry = archive.CreateEntry(name, CompressionLevel.Optimal);
        using var writer = new StreamWriter(entry.Open(), new UTF8Encoding(false));
        writer.Write(content);
    }

    private static string BuildReadme(GitHubUser user, string templateName, int variant) =>
$@"# {user.Name ?? user.Login} — Portfolio

A static portfolio site generated by PortfolioForge on {DateTime.UtcNow:yyyy-MM-dd}.

**Theme:** {templateName} (variant {variant + 1})
**Source:** github.com/{user.Login}

## Run locally

Open `index.html` in a browser. That's it.

## Deploy

Drop all three files (`index.html`, `style.css`, `script.js`) onto any static host:

- **GitHub Pages:** push to a `gh-pages` branch or set the source in repo settings
- **Netlify / Vercel / Cloudflare Pages:** drag-and-drop the folder
- **Azure Static Web Apps:** point a Static Web App at the folder, or upload via Azure CLI

## Customize

Edit `style.css` to tweak colors, fonts, spacing. The HTML structure is intentionally simple — feel free to rearrange.

---

Generated by PortfolioForge. Re-roll any time.
";
}
